### ISSUE TITLE
[css-lists][css-pseudo] Add ::marker to interface CSSPseudoElement

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#10]
A resolution was made for [csswg-drafts/#3763](https://github.com/w3c/csswg-drafts/issues/3763).

**\[css\-lists\]\[css\-pseudo\] Add ::marker to interface CSSPseudoElement**

* RESOLVED: Add ::marker to interface CSSPseudoElement

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3763#issuecomment-481773782)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We support this already.
