### ISSUE TITLE
[css-shapes-2] The readiness to ship for new path() function

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#101]
A resolution was made for [csswg-drafts/#4271](https://github.com/w3c/csswg-drafts/issues/4271).

**\[css\-shapes\-2\] The readiness to ship for new path\(\) function**

* RESOLVED: Impls can ship clip\-path:path\(\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4271#issuecomment-531681208)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1488530.
