### ISSUE TITLE
[css-transforms-1] Add accessibility section

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#102]
A resolution was made for [csswg-drafts/#3870](https://github.com/w3c/csswg-drafts/issues/3870).

**\[css\-transforms\-1\] Add accessibility section**

* RESOLVED: Remove section on animation and wontfix issue about paragraph about accessibility because no longer relevant

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3870#issuecomment-532038102)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
Nothing to do.
