### ISSUE TITLE
[css-fonts-5] Dynamic text size

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#105]
A resolution was made for [csswg-drafts/#3708](https://github.com/w3c/csswg-drafts/issues/3708).

**\[css\-fonts\-5\] Dynamic text size**

* RESOLVED: There should be a way to have true font sizes.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3708#issuecomment-532091468)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
No specific proposal yet.
