### ISSUE TITLE
[css-fonts] system-ui-serif, system-ui-monospaced, and system-ui-rounded

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#108]
A resolution was made for [csswg-drafts/#4107](https://github.com/w3c/csswg-drafts/issues/4107).

**\[css\-fonts\] system\-ui\-serif, system\-ui\-monospaced, and system\-ui\-rounded**

* RESOLVED: Add them with the \`ui\-\` prefix and make them not match if they're not available

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4107#issuecomment-532111422)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
There are bugs on file about this: [1598879](https://bugzilla.mozilla.org/show_bug.cgi?id=1598879), [1598880](https://bugzilla.mozilla.org/show_bug.cgi?id=1598880), [1598881](https://bugzilla.mozilla.org/show_bug.cgi?id=1598881), [1598883](https://bugzilla.mozilla.org/show_bug.cgi?id=1598883)
