### ISSUE TITLE
[css-tables] Calc for table layout

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#109]
A resolution was made for [csswg-drafts/#94](https://github.com/w3c/csswg-drafts/issues/94).

**\[css\-tables\] Calc for table layout**

* RESOLVED: Any math expression of a complex type is treated as auto.  Simple typed things continue to work as today.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/94#issuecomment-532128184)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
This is what we do.
