### ISSUE TITLE
[css-lists-3] Should unicode-bidi / direction apply to ::marker?

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#11]
A resolution was made for [csswg-drafts/#3809](https://github.com./w3c/csswg-drafts/issues/3809).

**\[css\-lists\-3\] Should unicode\-bidi / direction apply to ::marker?**

* RESOLVED: unicode\-bidi / direction apply to ::marker

[Discussion.](https://github.com./w3c/csswg-drafts/issues/3809#issuecomment-481754712)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
According to my brief test, we currently apply `direction` but not `unicode-bidi`.

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1551791
