### ISSUE TITLE
[css-pseudo-4] Proposal: Highlight API

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#110]
A resolution was made for [csswg-drafts/#4307](https://github.com/w3c/csswg-drafts/issues/4307).

**\[css\-pseudo\-4\] Proposal: Highlight API**

* RESOLVED: Adopt css\-highlight\-api as ED with sanketj, florian , and hober as editors; add issue into css\-pseudo\-4 for where it might be integrated pointing at the ED

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4307#issuecomment-536159854)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
No action needed.
