### ISSUE TITLE
[media-queries][css-sizing] Support <number> (and therefore calc) as a <ratio>

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#112]
A resolution was made for [csswg-drafts/#3757](https://github.com/w3c/csswg-drafts/issues/3757).

**\[media\-queries\]\[css\-sizing\] Support &lt;number&gt; \(and therefore calc\) as a &lt;ratio&gt;**

* RESOLVED: Accept proposal in favor of serializing with the calc expression

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3757#issuecomment-537722295)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We do this now.
