### ISSUE TITLE
writing-mode propagation from body to document element is annoying

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#116]
A resolution was made for [csswg-drafts/#4357](https://github.com/w3c/csswg-drafts/issues/4357).

**writing\-mode propagation from body to document element is annoying**

* RESOLVED: Close this issue no change

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4357#issuecomment-540075626)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
No new bug needed. We should proceed https://bugzilla.mozilla.org/show_bug.cgi?id=1102175
