### ISSUE TITLE
[resize-observer] device-pixel-border-box size

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#117]
A resolution was made for [csswg-drafts/#3554](https://github.com/w3c/csswg-drafts/issues/3554).

**\[resize\-observer\] device\-pixel\-border\-box size**

* RESOLVED: Add API to get content box height and width in device pixel sizes to resize observer. Only return when requested and applies to all element.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3554#issuecomment-540086408)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
As noted in the csswg discussion, "border-box" is probably wrong here -- authors would likely really want the *content-box* size (the size of the `<canvas>` canvas-API-drawable area in device pixels, when this is used on canvas).

**Comment by dholbert** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1587973
