### ISSUE TITLE
[css-grid-2][css-grid] `grid-template-rows/columns` Computed / Resolved Values for 'subgrid' values

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#119]
A resolution was made for [csswg-drafts/#4362](https://github.com/w3c/csswg-drafts/issues/4362).

**\[css\-grid\-2\]\[css\-grid\] \`grid\-template\-rows/columns\` Computed / Resolved Values for 'subgrid' values**

* RESOLVED: Accept Mat's proposal which is that resolved value unwraps repeat notations and does not insert track sizes for subgrid

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4362#issuecomment-540092172)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by MatsPalmgren** [comment]
We have a bug on file for this: https://bugzilla.mozilla.org/show_bug.cgi?id=1234311
