### ISSUE TITLE
[css-lists] Is the list-item counter increment for list items reflected in the computed style?

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#12]
A resolution was made for [csswg-drafts/#3769](https://github.com/w3c/csswg-drafts/issues/3769).

**\[css\-lists\] Is the list\-item counter increment for list items reflected in the computed style?**

* RESOLVED: implicit list\-item counter is not reflected in computed style

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3769#issuecomment-481773323)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We implement this change correctly.
