### ISSUE TITLE
Proposal: content-size CSS property

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#123]
A resolution was made for [csswg-drafts/#4229](https://github.com/w3c/csswg-drafts/issues/4229).

**Proposal: content\-size CSS property**

* RESOLVED: intrinsic\-size is the name of the new property and value set is 'auto', 'legacy' and a length

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4229#issuecomment-542781858)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
This was implemented in https://bugzilla.mozilla.org/show_bug.cgi?id=1597529 & related bugs.
