### ISSUE TITLE
[css-grid-2][css-grid] `grid-template-rows/columns` Computed / Resolved Values for 'subgrid' values

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#124]
A resolution was made for [csswg-drafts/#4362](https://github.com/w3c/csswg-drafts/issues/4362).

**\[css\-grid\-2\]\[css\-grid\] \`grid\-template\-rows/columns\` Computed / Resolved Values for 'subgrid' values**

* RESOLVED: Serialize the subgrid template rows and columns to only include line names defined for the subgrid locally and not include names that came from the parent grid

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4362#issuecomment-542786807)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
Should be covered by [Bug 1583429](https://bugzilla.mozilla.org/show_bug.cgi?id=1583429)
