### ISSUE TITLE
[css-transforms-2] Serialization of individual transform when the animation is at 0% or 100%

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#128]
A resolution was made for [csswg-drafts/#3290](https://github.com/w3c/csswg-drafts/issues/3290).

**\[css\-transforms\-2\] Serialization of individual transform when the animation is at 0% or 100%**

* RESOLVED: We return the values the animation is working on while the animation is going and that includes the endpoints per the definition in web animations

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3290#issuecomment-545536815)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
We may not need to update this for Gecko. Just need to update wpt.

**Comment by BorisChiou** [comment]
Bug 1506746 is for this issue, so we can close thie
