### ISSUE TITLE
[css-lists][css-pseudo] the 'content' property should apply to ::marker

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#13]
A resolution was made for [csswg-drafts/#3499](https://github.com./w3c/csswg-drafts/issues/3499).

**\[css\-lists\]\[css\-pseudo\] the 'content' property should apply to ::marker**

* RESOLVED: the 'content' property should apply to ::marker

[Discussion.](https://github.com./w3c/csswg-drafts/issues/3499#issuecomment-481775862)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
`content` applies to marker, but we also apply a bunch of extra properties, see #30.
