### ISSUE TITLE
ResizeObserverEntry either needs to have its JS constructor removed, or define how its members are initialized when constructed

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#135]
A resolution was made for [csswg-drafts/#3946](https://github.com/w3c/csswg-drafts/issues/3946).

**ResizeObserverEntry either needs to have its JS constructor removed, or define how its members are initialized when constructed**

* RESOLVED: To remove the constructor and remove the language about how to populate the object into a different point in the spec

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3946#issuecomment-550567232)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
No action needed, we don't have the constructor as it caused crashes as per the linked bug.
