### ISSUE TITLE
[css-fonts] Add a ui-sans-serif keyword to go with ui-serif

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#136]
A resolution was made for [csswg-drafts/#4468](https://github.com/w3c/csswg-drafts/issues/4468).

**\[css\-fonts\] Add a ui\-sans\-serif keyword to go with ui\-serif**

* RESOLVED: add ui\-sans\-serif

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4468#issuecomment-550569399)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
[1598880](https://bugzilla.mozilla.org/show_bug.cgi?id=1598880) is this.
