### ISSUE TITLE
[css-ui] Spec the pointer-events property for non-SVG elements

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#137]
A resolution was made for [csswg-drafts/#4438](https://github.com/w3c/csswg-drafts/issues/4438).

**\[css\-ui\] Spec the pointer\-events property for non\-SVG elements**

* RESOLVED: add pointer\-events to css\-ui level 4

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4438#issuecomment-550570928)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
Nothing to do.
