### ISSUE TITLE
[css-multicol] How do elements between column-span and its multicol ancestor appear around the span

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#14]
A resolution was made for [csswg-drafts/#1072](https://github.com/w3c/csswg-drafts/issues/1072).

**\[css\-multicol\] How do elements between column\-span and its multicol ancestor appear around the span**

* RESOLVED: Clarify the spec using the notion that this is an out of flow that leaves a forced break behind

[Discussion.](https://github.com/w3c/csswg-drafts/issues/1072#issuecomment-481784072)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
@Aethanyc Do we need a new bug filed for this, or do we already have this behavior?

**Comment by aethanyc** [comment]
Yes, I think our implementation already makes column-span act like an out of flow (though it still occupied the block dimension space of the column container.
