### ISSUE TITLE
[css-lists-3] counter-set vs counter-increment

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#15]
A resolution was made for [csswg-drafts/#3810](https://github.com/w3c/csswg-drafts/issues/3810).

**\[css\-lists\-3\] counter\-set vs counter\-increment**

* RESOLVED: apply counter\-set after counter\-increment

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3810#issuecomment-481756235)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We implement this change.
