### ISSUE TITLE
[css-lists] Initial value of counter-increment needs to be something different from none

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#16]
A resolution was made for [csswg-drafts/#3686](https://github.com./w3c/csswg-drafts/issues/3686).

**\[css\-lists\] Initial value of counter\-increment needs to be something different from none**

* RESOLVED: go with fantasai proposal \(a\) for initial value of counter increment?

[Discussion.](https://github.com./w3c/csswg-drafts/issues/3686#issuecomment-482612599)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
That's what we ended up doing.
