### ISSUE TITLE
[css-text] text-transform's design, intent and reality resolution

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#17]
A resolution was made for [csswg-drafts/#3775](https://github.com./w3c/csswg-drafts/issues/3775).

**\[css\-text\] text\-transform's design, intent and reality resolution**

* RESOLVED: normative state that text\-transform does not apply to plain text paste.

[Discussion.](https://github.com./w3c/csswg-drafts/issues/3775#issuecomment-480005535)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
I think that's what we do already, @jfkthame can probably confirm.

**Comment by jfkthame** [comment]
Yes, we do. The main issue is that although there has been a WG resolution (a year ago), Blink is reluctant to conform to it.

Nothing for us to do here except continue to defend the spec'd behavior, which we believe to be correct.
