### ISSUE TITLE
[css-values] minimum nested pairs of parentheses in calc to 32

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#18]
Resolutions were made for [csswg-drafts/#3462](https://github.com./w3c/csswg-drafts/issues/3462).

**\[css\-values\] minimum nested pairs of parentheses in calc to 32**

* RESOLVED: Set minimum number of parenthesis to 32
* RESOLVED: Raise the number of expressions that must be handled to 32

[Discussion.](https://github.com./w3c/csswg-drafts/issues/3462#issuecomment-484160903)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We support more than 32.
