### ISSUE TITLE
[various] Holistic review/proposal of color-modifying things

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#20]
Resolutions were made for [csswg-drafts/#3807](https://github.com/w3c/csswg-drafts/issues/3807).

**\[various\] Holistic review/proposal of color\-modifying things**

* RESOLVED: start a new Color Adjust draft
* RESOLVED: Add forced\-colors MQ to MQ spec
* RESOLVED: Add forced\-color\-adjust property as an opt to into new spec

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3807#issuecomment-484176211)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
Nothing actionable.
