### ISSUE TITLE
[various] Holistic review/proposal of color-modifying things

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#21]
Resolutions were made for [csswg-drafts/#3807](https://github.com/w3c/csswg-drafts/issues/3807).

**\[various\] Holistic review/proposal of color\-modifying things**

* RESOLVED: Add the color\-scheme property and meta with updated grammar and no 'only' property to Color Adjust spec instead of supported\-color\-scheme
* RESOLVED: Move print\-color\-adjust property into the new spec

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3807#issuecomment-484178262)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We may implement this in the future, but for now no change needed I think.
