### ISSUE TITLE
[css-pseudo-4] Should Element.pseudo("unknown") be an error or return null?

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#22]
A resolution was made for [csswg-drafts/#3603](https://github.com/w3c/csswg-drafts/issues/3603).

**\[css\-pseudo\-4\] Should Element.pseudo\("unknown"\) be an error or return null?**

* RESOLVED: Do a css parse on parameter for element.pseudo\(\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3603#issuecomment-484156093)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We don't yet implement this API.
