### ISSUE TITLE
[selectors-4] Need to allow stacked pseudo-element selectors in the grammar

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#23]
A resolution was made for [csswg-drafts/#3876](https://github.com/w3c/csswg-drafts/issues/3876).

**\[selectors\-4\] Need to allow stacked pseudo\-element selectors in the grammar**

* RESOLVED: Generic selector grammar allows stacking pseudo elements and classes. Only certain combos will be made valid, by default everything is invalid

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3876#issuecomment-488482816)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We already allow them in practice.
