### ISSUE TITLE
[css-text] impact of unstyled inlines on hyphenation

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#28]
A resolution was made for [csswg-drafts/#3862](https://github.com/w3c/csswg-drafts/issues/3862).

**\[css\-text\] impact of unstyled inlines on hyphenation**

* RESOLVED: out\-of\-flows don't affect hyphenation

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3862#issuecomment-490557524)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
Nightly behaves correctly:

`data:text/html,<div lang="en" style="width: 0; hyphens: auto">high<span style="font-size: 130%">way</span>`

So closing.
