### ISSUE TITLE
[css-pseudo-4] should CSSPseudoElement have a pseudo() method?

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#29]
A resolution was made for [csswg-drafts/#3836](https://github.com/w3c/csswg-drafts/issues/3836).

**\[css\-pseudo\-4\] should CSSPseudoElement have a pseudo\(\) method?**

* RESOLVED: add .pseudo\(\) to CSSPseudoElement once some stacked pseudo combination becomes a valid selector. Adjust .element return type to match.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3836#issuecomment-490559213)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
Resolution implies no action needed for now.
