### ISSUE TITLE
[css-lists] Interaction of ::marker with other pseudo-elements.

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#30]
A resolution was made for [csswg-drafts/#3826](https://github.com/w3c/csswg-drafts/issues/3826).

**\[css\-lists\] Interaction of ::marker with other pseudo\-elements.**

* RESOLVED: don't expand the list of props that apply to ::marker

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3826#issuecomment-490561772)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
Need to file a bug to restrict properties that apply to ::marker, will do later, but feel free to nag me if I don't.

**Comment by MatsPalmgren** [comment]
FTR, [I'm opposed](https://github.com/w3c/csswg-drafts/issues/3826#issuecomment-485149112) to introducing arbitrary unnecessary styling restrictions on `::marker`. IMO, we shouldn't restrict it unless there are very strong reasons to do so. AFAIK, no one has provided any arguments for why styling `::marker` needs to be restricted.

I think we should consider objecting to this resolution.

**Comment by emilio** [comment]
The argument from @fantasai was that marker layout was not sufficiently defined. It's trivial to add that restriction at the style system level for now (much like `::placeholder` and `::first-line` also have their own restrictions) and lift it when the working group agrees.

**Comment by emilio** [comment]
The restrictions landed, there's a pref to disable them when needed.
