### ISSUE TITLE
[css-scroll-snap-1] Clarify which writing-mode is used for scroll-snap-align, scroll container or snap position element?

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#31]
A resolution was made for [csswg-drafts/#3815](https://github.com/w3c/csswg-drafts/issues/3815).

**\[css\-scroll\-snap\-1\] Clarify which writing\-mode is used for scroll\-snap\-align, scroll container or snap position element?**

* RESOLVED: use the writing mode of the container

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3815#issuecomment-490563414)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
Just to confirm @hiikezoe that this resolution is already covered by https://bugzilla.mozilla.org/show_bug.cgi?id=1546835?

**Comment by hiikezoe** [comment]
To be precise, it was covered in the first place when we implemented scroll-snap-align in https://bugzilla.mozilla.org/show_bug.cgi?id=1373835.  I did trust Jonathan Kew. :)
