### ISSUE TITLE
[cssom] Figure out what to do with non-standard CSSStyleSheet methods in WebKit / Blink

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#32]
A resolution was made for [csswg-drafts/#3814](https://github.com/w3c/csswg-drafts/issues/3814).

**\[cssom\] Figure out what to do with non\-standard CSSStyleSheet methods in WebKit / Blink**

* RESOLVED: Spec these methods, mark them deprecated, add ADVISEMENT to authors to not teach or use

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3814#issuecomment-490566018)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
This is being done in https://bugzilla.mozilla.org/show_bug.cgi?id=1545823.
