### ISSUE TITLE
[css-overflow-3] Define how child margin-boxes contributes to scrollable overflow (ISSUE 6)

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#33]
A resolution was made for [csswg-drafts/#3653](https://github.com/w3c/csswg-drafts/issues/3653).

**\[css\-overflow\-3\] Define how child margin\-boxes contributes to scrollable overflow \(ISSUE 6\)**

* RESOLVED: for flex and grid, margins contribute to overflow

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3653#issuecomment-490567924)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
This is covered by https://bugzilla.mozilla.org/show_bug.cgi?id=1527539.
