### ISSUE TITLE
[css-text] inline elements should not introduce a forced line break or soft wrap opportunity

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#34]
A resolution was made for [csswg-drafts/#3886](https://github.com/w3c/csswg-drafts/issues/3886).

**\[css\-text\] inline elements should not introduce a forced line break or soft wrap opportunity**

* RESOLVED: Inline box boundaries don't affect line breaking opportunities

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3886#issuecomment-490550042)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
Everybody does this according to that issue.
