### ISSUE TITLE
[selectors-4] Rescope :has to static CSS rather than .querySelector

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#36]
A resolution was made for [csswg-drafts/#3925](https://github.com/w3c/csswg-drafts/issues/3925).

**\[selectors\-4\] Rescope :has to static CSS rather than .querySelector**

* RESOLVED: Mark this as at risk and optional, remove profile

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3925#issuecomment-492724267)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We don't implement :has.
