### ISSUE TITLE
[css-sizing] The resolved value of min-size: auto should also be 0 when there is no box

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#37]
A resolution was made for [csswg-drafts/#3557](https://github.com/w3c/csswg-drafts/issues/3557).

**\[css\-sizing\] The resolved value of min\-size: auto should also be 0 when there is no box**

* RESOLVED: The resolved value of min\-size: auto is 0 when there is no box

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3557#issuecomment-494869747)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
Seems we already do this.
