### ISSUE TITLE
[css-images-4] Color stop fixup: do interpolation hints function as positioned color stops?

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#38]
A resolution was made for [csswg-drafts/#3931](https://github.com/w3c/csswg-drafts/issues/3931).

**\[css\-images\-4\] Color stop fixup: do interpolation hints function as positioned color stops?**

* RESOLVED: Make spec match browsers on color hints / positions

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3931#issuecomment-494876538)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
Seems that no change to Gecko is needed.
