### ISSUE TITLE
[css-values-3] serialization of fragment URLs in image properties

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#40]
A resolution was made for [csswg-drafts/#3195](https://github.com/w3c/csswg-drafts/issues/3195).

**\[css\-values\-3\] serialization of fragment URLs in image properties**

* RESOLVED: no change to URL serialization for fragment\-only URLS

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3195#issuecomment-494882821)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We have a bug on file for this already, noted in the minutes.
