### ISSUE TITLE
[css-sizing-3] Rename spec to CSS Box Sizing

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#41]
A resolution was made for [csswg-drafts/#3962](https://github.com/w3c/csswg-drafts/issues/3962).

**\[css\-sizing\-3\] Rename spec to CSS Box Sizing**

* RESOLVED: remane Box Intrinsic Sizing to Box Sizing with no change in shortname

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3962#issuecomment-497002003)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dbaron** [comment]
No bug needed.
