### ISSUE TITLE
[css-color-adjust-1] Add 'color-scheme: auto'?

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#44]
A resolution was made for [csswg-drafts/#3849](https://github.com/w3c/csswg-drafts/issues/3849).

**\[css\-color\-adjust\-1\] Add 'color\-scheme: auto'?**

* RESOLVED: Add color\-scheme: normal

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3849#issuecomment-497023412)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We don't implement the color-scheme property yet at least.
