### ISSUE TITLE
[selectors-4] additional resource state pseudo-classes for media elements

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#45]
A resolution was made for [csswg-drafts/#3821](https://github.com/w3c/csswg-drafts/issues/3821).

**\[selectors\-4\] additional resource state pseudo\-classes for media elements**

* RESOLVED: Add :muted, :seeking, and :stalled pseudos.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3821#issuecomment-498683965)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
cc @padenot, do you want a bug on file for this? In particular, do you plan to implement / request us to implement these in the nearish future?

**Comment by padenot** [comment]
Thanks, filed [BMO#1565573](https://bugzilla.mozilla.org/show_bug.cgi?id=1565572). Unclear if we plan to do it now, but it's probably very easy.

**Comment by emilio** [comment]
Alright, closing this then.
