### ISSUE TITLE
[selectors-4] "effective media volume is mutable" pseudo-class for media elements

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#46]
A resolution was made for [csswg-drafts/#3933](https://github.com/w3c/csswg-drafts/issues/3933).

**\[selectors\-4\] "effective media volume is mutable" pseudo\-class for media elements**

* RESOLVED: Add :volume\-locked.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3933#issuecomment-498689912)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
cc @padenot, want a bug on file for this?

**Comment by padenot** [comment]
Thanks, filed [BMO#1565573](https://bugzilla.mozilla.org/show_bug.cgi?id=1565573).
