### ISSUE TITLE
[selectors-4] Password reveal pseudo-element and pseudo-class

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#47]
A resolution was made for [csswg-drafts/#3934](https://github.com/w3c/csswg-drafts/issues/3934).

**\[selectors\-4\] Password reveal pseudo\-element and pseudo\-class**

* RESOLVED: input\-security: auto&124;none in UI 4 and applies to input type=password only

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3934#issuecomment-498712344)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
cc @masayuki-nakano, does this impact your plans for `input[type=password]`? My understanding is "not", but let me know if it does.

**Comment by masayuki-nakano** [comment]
@emilio Yes, I say "no". But sounds like that new design allows us to implement it really easier.
(And I think that there should be a new attribute to do it with built-in UI)
