### ISSUE TITLE
[css-fonts] consider not making font-min-size and font-max-size affect font-size computed value

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#48]
A resolution was made for [csswg-drafts/#3739](https://github.com/w3c/csswg-drafts/issues/3739).

**\[css\-fonts\] consider not making font\-min\-size and font\-max\-size affect font\-size computed value**

* RESOLVED: Remove min\-font\-size and max\-font\-size from Fonts 4, replace with an example of using clamp\(\) to handle safe responsive typography.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3739#issuecomment-498789037)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
Nothing to do, we don't (and nobody does) implement this.
