### ISSUE TITLE
[css-fonts] Clarify how the computed font-size is determined for size keyword

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#49]
Resolutions were made for [csswg-drafts/#3906](https://github.com/w3c/csswg-drafts/issues/3906).

**\[css\-fonts\] Clarify how the computed font\-size is determined for size keyword**

* RESOLVED: Capture that font\-size keywords carry an additional bit of information having some \(unspecified\) interaction with some font families.
* RESOLVED: François does compat research on the effect of font\-size keywords and generic font\-families, and report back on interop.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3906#issuecomment-498793666)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
Nothing actionable for now looks like.
