### ISSUE TITLE
[css-multicol] column-gap <length-percentage> remove at-risk marker

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#50]
A resolution was made for [csswg-drafts/#3988](https://github.com/w3c/csswg-drafts/issues/3988).

**\[css\-multicol\] column\-gap &lt;length\-percentage&gt; remove at\-risk marker**

* RESOLVED: remove at\-risk percentages on column\-gap \(and add some tests\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3988#issuecomment-498825630)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
Not a normative change.
