### ISSUE TITLE
[css-multicol] Should we refer to definition of `column-gap` in Box Alignment?

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#51]
A resolution was made for [csswg-drafts/#3641](https://github.com/w3c/csswg-drafts/issues/3641).

**\[css\-multicol\] Should we refer to definition of \`column\-gap\` in Box Alignment?**

* RESOLVED: add an heading to explain how column\-gap works in multicol, but define in box\-alignment only

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3641#issuecomment-498827184)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
This seems editorial only.
