### ISSUE TITLE
[css-sizing-3] Why was min-content, etc. redefined to do nothing in the block axis?

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#52]
A resolution was made for [csswg-drafts/#3973](https://github.com/w3c/csswg-drafts/issues/3973).

**\[css\-sizing\-3\] Why was min\-content, etc. redefined to do nothing in the block axis?**

* RESOLVED: cbiesinger will document chrome's behavior and we will revisit

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3973#issuecomment-498841720)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
Nothing to do.
