### ISSUE TITLE
[css-text] For most languages, hyphens:auto should not hyphenate Capitalized words

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#54]
A resolution was made for [csswg-drafts/#3927](https://github.com/w3c/csswg-drafts/issues/3927).

**\[css\-text\] For most languages, hyphens:auto should not hyphenate Capitalized words**

* RESOLVED: Add A note to the spec and close with no normative change

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3927#issuecomment-499101864)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
Nothing to do here. We have recently tweaked Firefox behavior in this area, along the lines being suggested. May continue to refine this, but the spec leaves it up to the implementation.
