### ISSUE TITLE
[css-writing-modes] Does vertical writing mode of an HTML body element cause an orthogonal flow?

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#55]
A resolution was made for [csswg-drafts/#3066](https://github.com/w3c/csswg-drafts/issues/3066).

**\[css\-writing\-modes\] Does vertical writing mode of an HTML body element cause an orthogonal flow?**

* RESOLVED: proposed resolution: Propagate direction, and writing mode from the body to the root without affecting computed styles w/optional text\-orientation

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3066#issuecomment-499111764)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1102175.
