### ISSUE TITLE
[css-color-4] Color modifications proposal: extending color functions

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#56]
Resolutions were made for [csswg-drafts/#3187](https://github.com/w3c/csswg-drafts/issues/3187).

**\[css\-color\-4\] Color modifications proposal: extending color functions**

* RESOLVED: Put all the proposals into css\-color\-5, ChrisL and future Una as editors
* RESOLVED: Rename to put 'color' first, adjust\-color \-&gt; color\-mod\(\)
* RESOLVED: Add color\-contrast\(\) without currentbg
* RESOLVED: Add color\-mix\(\), try to align with cross\-fade\(\)
* RESOLVED: Put both color adjustment proposals into css\-color\-5, with keywords instead of css\-color\-5
* RESOLVED: Add Lea Verou as editor of css\-color\-5

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3187#issuecomment-499206254)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We don't implement these yet, so I'm not sure it's useful to file a bug for this.

@heycam should we clarify whether we're expected to file bugs for new features we don't yet implement?
