### ISSUE TITLE
[css-backgrounds-4] Borders with cut corners

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#57]
Resolutions were made for [csswg-drafts/#3457](https://github.com/w3c/csswg-drafts/issues/3457).

**\[css\-backgrounds\-4\] Borders with cut corners**

* RESOLVED: Add Florian as editor of css\-text\-4
* RESOLVED: drop the less useful values, and rename as proposed in the issue

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3457#issuecomment-499217243)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We don't implement these yet, so I'm not sure a bug on file is on point for these.
