### ISSUE TITLE
[css-color-adjust-1][mediaqueries-5] Clearly define what 'light' and 'dark' mean

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#58]
Resolutions were made for [csswg-drafts/#3983](https://github.com/w3c/csswg-drafts/issues/3983).

**\[css\-color\-adjust\-1\]\[mediaqueries\-5\] Clearly define what 'light' and 'dark' mean**

* RESOLVED: Add a note to color\-scheme to warn authors that the exact colors for dark and light mode are not specified, and that if they need to guarantee contrast against their own colors, they need to specify both foreground and background pairs.
* RESOLVED: Add a note to color\-scheme to warn authors that dark and light modes are not necessarily black and white colors, and that if they are specifying any of their own colors they should specify enough colors to satisfy WCAG requirements \(with a link\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3983#issuecomment-499240804)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
Bikeshedding with no change to our implementation for now, afaict.
