### ISSUE TITLE
[css-color-adjust-1] possible future <custom-ident> value 'sepia'

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#59]
A resolution was made for [csswg-drafts/#3853](https://github.com/w3c/csswg-drafts/issues/3853).

**\[css\-color\-adjust\-1\] possible future &lt;custom\-ident&gt; value 'sepia'**

* RESOLVED: No change

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3853#issuecomment-499249648)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
No bug needed.
