### ISSUE TITLE
[css-sizing-4] Does aspect-ratio work on the content box or the border box?

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#60]
A resolution was made for [csswg-drafts/#4007](https://github.com/w3c/csswg-drafts/issues/4007).

**\[css\-sizing\-4\] Does aspect\-ratio work on the content box or the border box?**

* RESOLVED: Explicit a\-r applies to whichever box the box\-sizing property specifies.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4007#issuecomment-499494660)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We don't implement explicit aspect-ratio yet.
