### ISSUE TITLE
[css-nav-1] Predefined algorithm for spatial navigation

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#61]
A resolution was made for [csswg-drafts/#3964](https://github.com/w3c/csswg-drafts/issues/3964).

**\[css\-nav\-1\] Predefined algorithm for spatial navigation**

* RESOLVED: Add spatial\-navigation\-function to the spec

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3964#issuecomment-499536668)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We don't implement css-nav afaik.
