### ISSUE TITLE
[media-queries][css-sizing] Support <number> (and therefore calc) as a <ratio>

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#62]
Resolutions were made for [csswg-drafts/#3757](https://github.com/w3c/csswg-drafts/issues/3757).

**\[media\-queries\]\[css\-sizing\] Support &lt;number&gt; \(and therefore calc\) as a &lt;ratio&gt;**

* RESOLVED: change &lt;integer&gt; to &lt;number&gt; in the aspect\-ratio
* RESOLVED: allow &lt;number&gt; and &lt;number&gt;/&lt;number&gt; both for &lt;aspect\-ratio&gt;

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3757#issuecomment-499625710)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We need to update the media query parser. Should be an easy fix.

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1565562
