### ISSUE TITLE
[css-display] Parent box of run-in or non-principal box

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#63]
A resolution was made for [csswg-drafts/#3158](https://github.com/w3c/csswg-drafts/issues/3158).

**\[css\-display\] Parent box of run\-in or non\-principal box**

* RESOLVED: Republish Display

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3158#issuecomment-503626745)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We don't implement run-in, and the resolution isn't any change to the spec anyway.
