### ISSUE TITLE
[css-grid] How to distribute space using flex ratios when the sum is 0?

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#64]
A resolution was made for [csswg-drafts/#3694](https://github.com/w3c/csswg-drafts/issues/3694).

**\[css\-grid\] How to distribute space using flex ratios when the sum is 0?**

* RESOLVED: Accept change in https://github.com/w3c/csswg-drafts/commit/5a43ab7210d08c9a012a7697eb39a382f8133079

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3694#issuecomment-503627854)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
@MatsPalmgren: perhaps you could take a look and file a bug if needed?

**Comment by MatsPalmgren** [comment]
We already implement this resolution:
https://searchfox.org/mozilla-central/rev/05db7b82d5a4adaa8b36ec6f4fd1715f6fd7885b/layout/generic/nsGridContainerFrame.cpp#5735

**Comment by emilio** [comment]
Alright, then this should be closed.
