### ISSUE TITLE
[css-color-adjust-1] Disallow repetition of color-scheme keywords?

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#67]
A resolution was made for [csswg-drafts/#3848](https://github.com/w3c/csswg-drafts/issues/3848).

**\[css\-color\-adjust\-1\] Disallow repetition of color\-scheme keywords?**

* RESOLVED: computed value of color\-scheme match its specified value

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3848#issuecomment-503633417)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We don't implement this yet. When we do we'll account for this.
