### ISSUE TITLE
[css-text-decor] text-decoration level 4 clarification on text-underline-offset positive/negative lengths

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#68]
A resolution was made for [csswg-drafts/#4021](https://github.com/w3c/csswg-drafts/issues/4021).

**\[css\-text\-decor\] text\-decoration level 4 clarification on text\-underline\-offset positive/negative lengths**

* RESOLVED: Update the spec so positive offsets are outward from the text

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4021#issuecomment-505953321)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
This was implemented already.
