### ISSUE TITLE
[css-backgrounds-3] Computed value of background-size includes missing autos

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#70]
A resolution was made for [csswg-drafts/#2574](https://github.com/w3c/csswg-drafts/issues/2574).

**\[css\-backgrounds\-3\] Computed value of background\-size includes missing autos**

* RESOLVED: No change to spec

[Discussion.](https://github.com/w3c/csswg-drafts/issues/2574#issuecomment-505960214)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
... and we fixed Gecko already.
