### ISSUE TITLE
[css-lists] Should option/optgroup be able to set counters?

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#71]
A resolution was made for [csswg-drafts/#4004](https://github.com/w3c/csswg-drafts/issues/4004).

**\[css\-lists\] Should option/optgroup be able to set counters?**

* RESOLVED: leave undefined for now and add a note explaining why

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4004#issuecomment-508287146)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
No change needed.
