### ISSUE TITLE
[css-color-4] Predefined colorspaces

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#72]
A resolution was made for [csswg-drafts/#4056](https://github.com/w3c/csswg-drafts/issues/4056).

**\[css\-color\-4\] Predefined colorspaces**

* RESOLVED: Take what we're calling image\-p3 in our spec and rename it to display\-p3

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4056#issuecomment-508288347)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
We don't implement image-p3 so nothing to rename.
