### ISSUE TITLE
[css-content] Initial value of quotes should be auto

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#73]
A resolution was made for [csswg-drafts/#4074](https://github.com/w3c/csswg-drafts/issues/4074).

**\[css\-content\] Initial value of quotes should be auto**

* RESOLVED: Add an 'auto' value

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4074#issuecomment-508289873)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1421938.
