### ISSUE TITLE
[css-values-4] How to interpolate min/max/clamp?

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#74]
A resolution was made for [csswg-drafts/#4082](https://github.com/w3c/csswg-drafts/issues/4082).

**\[css\-values\-4\] How to interpolate min/max/clamp?**

* RESOLVED: For interpolation math functions are treated as atomic algebraic terms. You interpolate a calc expression that is the weighted sum of all the terms

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4082#issuecomment-510126631)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
This is just something we'll have to account for when we implement these.
