### ISSUE TITLE
[css-images] Computed gradient colors

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#75]
A resolution was made for [csswg-drafts/#4042](https://github.com/w3c/csswg-drafts/issues/4042).

**\[css\-images\] Computed gradient colors**

* RESOLVED: Add section to CSS images defining computed value of an image type. This value has colors links and lengths all made absolute per usual computed value rules for those sub types and fix specs referring to images to make sure use correct language

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4042#issuecomment-510130157)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dbaron** [comment]
My understanding from the discussion is that this will require other browsers to change to match Gecko's current behavior, although it might be worth doing a bit of testing to check.

**Comment by emilio** [comment]
Yes, that's my understanding too.

**Comment by yisibl** [comment]
Is there a Firefox bug for this?

**Comment by jfkthame** [comment]
From the discussion and dbaron's/emilio's comments above, it looks to me like Firefox has the desired behavior already (and so no bug would be required).

If that's **not** the case (e.g. are there relevant tests that Firefox fails?), please feel free to file a bug with details.
