### ISSUE TITLE
[resize-observer] svg interaction

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#76]
A resolution was made for [csswg-drafts/#4032](https://github.com/w3c/csswg-drafts/issues/4032).

**\[resize\-observer\] svg interaction**

* RESOLVED: svg elements generating css layout boxes are included as part of resize observer and resize observer rectangles with a definition of \`svg:root, \*:not\(svg&124;\*\) &gt; svg, svg&124;foreignObject &gt; svg { /\* SVG elements with CSS layout box \*/}

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4032#issuecomment-510137495)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
@heycam it looks like the bot needs to un-html-escape stuff :)

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1565557
