### ISSUE TITLE
[css-shapes] Accept percentage for shape-image-threshold

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#80]
A resolution was made for [csswg-drafts/#4102](https://github.com/w3c/csswg-drafts/issues/4102).

**\[css\-shapes\] Accept percentage for shape\-image\-threshold**

* RESOLVED: Treat shape\-image\-threshold as an opacity prop and allow %

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4102#issuecomment-514715223)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1568615

**Comment by BorisChiou** [comment]
So convenient. :)
