### ISSUE TITLE
[css-images][css-masking][paint] Ambiguities in handling url()

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#82]
Resolutions were made for [csswg-drafts/#383](https://github.com/w3c/csswg-drafts/issues/383).

**\[css\-images\]\[css\-masking\]\[paint\] Ambiguities in handling url\(\)**

* RESOLVED: treat fragment only URLs as only elements, never images
* RESOLVED: Change requirements from 'should' to 'must'
* RESOLVED: Add the edits in https://drafts.csswg.org/css\-images\-3/\#ambiguous\-urls

[Discussion.](https://github.com/w3c/csswg-drafts/issues/383#issuecomment-516927986)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
I don't think this needs changes to our impl.
