### ISSUE TITLE
[css-images] Should the values of image-orientation include the <angle> variants?

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#89]
A resolution was made for [csswg-drafts/#4164](https://github.com/w3c/csswg-drafts/issues/4164).

**\[css\-images\] Should the values of image\-orientation include the &lt;angle&gt; variants?**

* RESOLVED: Update note saying this is not for implementation and will be dropped

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4164#issuecomment-521325222)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We unshipped these.
