### ISSUE TITLE
[css-values-4] How to serialize infinite values?

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#9]
A resolution was made for [csswg-drafts/#3768](https://github.com/w3c/csswg-drafts/issues/3768).

**\[css\-values\-4\] How to serialize infinite values?**

* RESOLVED: Use calc\(1/0\) and calc\(0/0\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3768#issuecomment-481771424)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We don't implement the advanced calc math stuff yet.
