### ISSUE TITLE
[css-lists-3] counter(name, none) should be invalid

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#90]
A resolution was made for [csswg-drafts/#4163](https://github.com/w3c/csswg-drafts/issues/4163).

**\[css\-lists\-3\] counter\(name, none\) should be invalid**

* RESOLVED: Update to match 2.1 and make counter\(name, none\) invalid

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4163#issuecomment-521331100)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We seem to parse this.

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1576821
