### ISSUE TITLE
[CSS-images] Specify fallback behavior when replaced or background image content not available

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#91]
A resolution was made for [csswg-drafts/#1984](https://github.com/w3c/csswg-drafts/issues/1984).

**\[CSS\-images\] Specify fallback behavior when replaced or background image content not available**

* RESOLVED: Loading images are not invalid but treated similarly as explained in https://drafts.csswg.org/css\-images\-3/\#image\-values

[Discussion.](https://github.com/w3c/csswg-drafts/issues/1984#issuecomment-523539886)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
I think this matches our implementation. https://drafts.csswg.org/css-images-3/#invalid-image
