### ISSUE TITLE
[css-lists-3] Compute non-existent `list-style-type` <counter-style> to `decimal`?

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#94]
A resolution was made for [csswg-drafts/#4210](https://github.com/w3c/csswg-drafts/issues/4210).

**\[css\-lists\-3\] Compute non\-existent \`list\-style\-type\` &lt;counter\-style&gt; to \`decimal\`?**

* RESOLVED: No change re computed value of list\-style\-type

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4210#issuecomment-528137325)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
No change.
