### ISSUE TITLE
Proposal: content-size CSS property

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#96]
A resolution was made for [csswg-drafts/#4229](https://github.com/w3c/csswg-drafts/issues/4229).

**Proposal: content\-size CSS property**

* RESOLVED: Add proxy\-width/height/inline\-size/block\-size with values legacy &124; auto &124; &lt;length&gt;

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4229#issuecomment-531615054)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
Nothing to do yet.

**Comment by MatsPalmgren** [comment]
Fwiw, after reading the notes it's unclear to me what this property is meant to do. At the start of the discussion it's a way to specify a size for `contain:size` only. Then dbaron suggested it could apply in general. It's unclear what the consensus is at the end...
