### ISSUE TITLE
[css-scroll-anchoring-1] Can anchor node be an inline-block?

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#97]
Resolutions were made for [csswg-drafts/#4247](https://github.com/w3c/csswg-drafts/issues/4247).

**\[css\-scroll\-anchoring\-1\] Can anchor node be an inline\-block?**

* RESOLVED: An anchor node only can be every box except a non\-atomic inline box
* RESOLVED: An anchor node can be any box except non\-atomic inline boxes

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4247#issuecomment-531638924)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
Fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1540203
