### ISSUE TITLE
[css-multicol] column-fill should behave more similarly in paginated and continuous contexts

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#98]
Resolutions were made for [csswg-drafts/#4036](https://github.com/w3c/csswg-drafts/issues/4036).

**\[css\-multicol\] column\-fill should behave more similarly in paginated and continuous contexts**

* RESOLVED: revert the change made in \#3224, and add spec issues to define this
* RESOLVED: republish the wd of css\-multicol

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4036#issuecomment-531646703)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dbaron** [comment]
Nothing needed here; this is resolutions in the direction of compatibility with what we already do.
