### ISSUE TITLE
[css-shapes-2] The new definition of '<basic-shape>' should include 'path()'

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#99]
A resolution was made for [csswg-drafts/#4270](https://github.com/w3c/csswg-drafts/issues/4270).

**\[css\-shapes\-2\] The new definition of '&lt;basic\-shape&gt;' should include 'path\(\)'**

* RESOLVED: Move path\(\) down to Shapes 1, adding it to &lt;basic\-shape&gt;.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4270#issuecomment-531669816)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
Spec editing process issue, no bug needed.
